# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [4]:
5*np.ones(10)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [5]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [6]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
nr = np.arange(9)
np.reshape(nr,(3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [9]:
np.random.rand()

0.7649687304766641

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [10]:
np.random.randn(25)

array([ 0.19746108,  0.91393872, -0.26377705,  1.2129579 , -0.59497993,
        1.49115866,  0.46078614, -0.99715579,  1.04781191,  0.16265373,
       -0.79005978, -1.26802594, -0.01085474,  1.28736623,  1.42138377,
        0.62468485, -0.20732247, -0.4905209 ,  1.33765664, -0.12095269,
       -0.64411915, -0.13122136, -0.5872833 , -0.02084891, -0.8016538 ])

#### Create the following matrix:

In [11]:
nrp = np.random.rand(100)
np.reshape(nrp,(10,10))
#np.random.random_sample((10,10))

array([[0.42906359, 0.59999894, 0.1005245 , 0.23181997, 0.85132779,
        0.14731757, 0.03575242, 0.43972493, 0.57413463, 0.93410107],
       [0.95161883, 0.87700594, 0.81625619, 0.17086234, 0.26462759,
        0.08411843, 0.08264766, 0.45440595, 0.13876696, 0.77606206],
       [0.49642582, 0.36833744, 0.58408973, 0.35258947, 0.76955293,
        0.78130227, 0.40596855, 0.97852842, 0.99351997, 0.32487495],
       [0.05464536, 0.6140483 , 0.10325434, 0.02002018, 0.77105819,
        0.6875211 , 0.88847406, 0.73465692, 0.73386063, 0.4834666 ],
       [0.81556745, 0.8364936 , 0.128286  , 0.18226737, 0.38324283,
        0.05317122, 0.95676924, 0.18687249, 0.33815439, 0.21120163],
       [0.86481528, 0.45250419, 0.35177924, 0.1932921 , 0.70911043,
        0.78561432, 0.36962628, 0.95995321, 0.27574525, 0.94617599],
       [0.42199765, 0.54952205, 0.94024018, 0.02320467, 0.20924509,
        0.46042106, 0.07747319, 0.47396785, 0.63769669, 0.92151176],
       [0.32665059, 0.52914907, 0.8897162

#### Create an array of 20 linearly spaced points between 0 and 1:

In [12]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [13]:
mat_np = np.arange(1,26)
mat = np.reshape(mat_np,(5,5))
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [14]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [15]:
mat[3,4]

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [16]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [17]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [18]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [19]:
np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [20]:
np.std(mat)

7.211102550927978

#### Get the sum of all the columns in mat

In [21]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])

# Great Job!